model_list:
  - model_name: gemini-flash
    litellm_params:
      model: gemini/gemini-3-flash-preview
      api_key: os.environ/GEMINI_API_KEY

  - model_name: gemini-flash-fallback
    litellm_params:
      model: gemini/gemini-3.1-flash-lite-preview
      api_key: os.environ/GEMINI_API_KEY

router_settings:
  routing_strategy: least-busy
  fallbacks: [{"gemini-flash": ["gemini-flash-fallback"]}]

litellm_settings:
  success_callback: ["langfuse", "prometheus"]
  failure_callback: ["langfuse", "prometheus"]

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY